export interface Language {
    code: string;
    flag: string;
    label: string;
    locale: string;
}

export const LANGUAGES: Language[] = [
    { code: 'ja', flag: '🇯🇵', label: '日本語', locale: 'ja-JP' },
    { code: 'en', flag: '🇺🇸', label: 'English (US)', locale: 'en-US' },
    { code: 'en-GB', flag: '🇬🇧', label: 'English (UK)', locale: 'en-GB' },
    { code: 'en-AU', flag: '🇦🇺', label: 'English (Australia)', locale: 'en-AU' },
    { code: 'zh-CN', flag: '🇨🇳', label: '中文 (简体)', locale: 'zh-CN' },
    { code: 'zh-TW', flag: '🇹🇼', label: '中文 (繁體)', locale: 'zh-TW' },
    { code: 'fr', flag: '🇫🇷', label: 'Français', locale: 'fr-FR' },
    { code: 'es', flag: '🇪🇸', label: 'Español', locale: 'es-ES' },
    { code: 'es-419', flag: '🇲🇽', label: 'Español (Latinoamérica)', locale: 'es-419' },
    { code: 'de', flag: '🇩🇪', label: 'Deutsch', locale: 'de-DE' },
    { code: 'it', flag: '🇮🇹', label: 'Italiano', locale: 'it-IT' },
    { code: 'ko', flag: '🇰🇷', label: '한국어', locale: 'ko-KR' },
    { code: 'pt', flag: '🇵🇹', label: 'Português', locale: 'pt-PT' },
    { code: 'pt-BR', flag: '🇧🇷', label: 'Português (Brasil)', locale: 'pt-BR' },
    { code: 'ru', flag: '🇷🇺', label: 'Русский', locale: 'ru-RU' },
    { code: 'vi', flag: '🇻🇳', label: 'Tiếng Việt', locale: 'vi-VN' },
    { code: 'ar', flag: '🇸🇦', label: 'العربية', locale: 'ar-SA' },
    { code: 'nl', flag: '🇳🇱', label: 'Nederlands', locale: 'nl-NL' },
    { code: 'pl', flag: '🇵🇱', label: 'Polski', locale: 'pl-PL' },
    { code: 'tr', flag: '🇹🇷', label: 'Türkçe', locale: 'tr-TR' },
    { code: 'th', flag: '🇹🇭', label: 'ไทย', locale: 'th-TH' },
    { code: 'id', flag: '🇮🇩', label: 'Bahasa Indonesia', locale: 'id-ID' },
    { code: 'sv', flag: '🇸🇪', label: 'Svenska', locale: 'sv-SE' },
    { code: 'no', flag: '🇳🇴', label: 'Norsk', locale: 'no-NO' },
    { code: 'fi', flag: '🇫🇮', label: 'Suomi', locale: 'fi-FI' },
    { code: 'da', flag: '🇩🇰', label: 'Dansk', locale: 'da-DK' },
    { code: 'he', flag: '🇮🇱', label: 'עברית', locale: 'he-IL' },
    { code: 'el', flag: '🇬🇷', label: 'Ελληνικά', locale: 'el-GR' },
    { code: 'cs', flag: '🇨🇿', label: 'Čeština', locale: 'cs-CZ' },
    { code: 'hu', flag: '🇭🇺', label: 'Magyar', locale: 'hu-HU' },
    { code: 'uk', flag: '🇺🇦', label: 'Українська', locale: 'uk-UA' },
    { code: 'ms', flag: '🇲🇾', label: 'Bahasa Melayu', locale: 'ms-MY' },
    { code: 'ro', flag: '🇷🇴', label: 'Română', locale: 'ro-RO' },
    { code: 'sk', flag: '🇸🇰', label: 'Slovenčina', locale: 'sk-SK' },
    { code: 'bg', flag: '🇧🇬', label: 'Български', locale: 'bg-BG' },
    { code: 'hr', flag: '🇭🇷', label: 'Hrvatski', locale: 'hr-HR' },
    { code: 'lt', flag: '🇱🇹', label: 'Lietuvių', locale: 'lt-LT' },
    { code: 'lv', flag: '🇱🇻', label: 'Latviešu', locale: 'lv-LV' },
    { code: 'et', flag: '🇪🇪', label: 'Eesti', locale: 'et-EE' },
    { code: 'sl', flag: '🇸🇮', label: 'Slovenščina', locale: 'sl-SI' },
    { code: 'tl', flag: '🇵🇭', label: 'Tagalog', locale: 'tl-PH' },
    { code: 'fa', flag: '🇮🇷', label: 'فارسی', locale: 'fa-IR' },
    { code: 'ur', flag: '🇵🇰', label: 'اردو', locale: 'ur-PK' },
    { code: 'bn', flag: '🇧🇩', label: 'বাংলা', locale: 'bn-BD' },
    { code: 'ta', flag: '🇱🇰', label: 'தமிழ்', locale: 'ta-LK' },
    { code: 'te', flag: '🇮🇳', label: 'తెలుగు', locale: 'te-IN' },
    { code: 'mr', flag: '🇮🇳', label: 'मराठी', locale: 'mr-IN' },
    { code: 'ml', flag: '🇮🇳', label: 'മലയാളം', locale: 'ml-IN' },
    { code: 'kn', flag: '🇮🇳', label: 'ಕನ್ನಡ', locale: 'kn-IN' },
    { code: 'gu', flag: '🇮🇳', label: 'ગુજરાતી', locale: 'gu-IN' },
    { code: 'pa', flag: '🇮🇳', label: 'ਪੰਜਾਬੀ', locale: 'pa-IN' },
    { code: 'sw', flag: '🇰🇪', label: 'Kiswahili', locale: 'sw-KE' },
    { code: 'yo', flag: '🇳🇬', label: 'Yorùbá', locale: 'yo-NG' },
    { code: 'ig', flag: '🇳🇬', label: 'Igbo', locale: 'ig-NG' },
    { code: 'ha', flag: '🇳🇬', label: 'Hausa', locale: 'ha-NG' },
    { code: 'so', flag: '🇸🇴', label: 'Soomaali', locale: 'so-SO' },
    { code: 'ne', flag: '🇳🇵', label: 'नेपाली', locale: 'ne-NP' },
    { code: 'si', flag: '🇱🇰', label: 'සිංහල', locale: 'si-LK' },
    { code: 'my', flag: '🇲🇲', label: 'မြန်မာ', locale: 'my-MM' },
    { code: 'km', flag: '🇰🇭', label: 'ភាសាខ្មែរ', locale: 'km-KH' },
    { code: 'lo', flag: '🇱🇦', label: 'ພາສາລາວ', locale: 'lo-LA' },
    { code: 'ka', flag: '🇬🇪', label: 'ქართული', locale: 'ka-GE' },
    { code: 'hy', flag: '🇦🇲', label: 'Հայերեն', locale: 'hy-AM' },
    { code: 'az', flag: '🇦🇿', label: 'Azərbaycanca', locale: 'az-AZ' },
    { code: 'kk', flag: '🇰🇿', label: 'Қазақша', locale: 'kk-KZ' },
    { code: 'uz', flag: '🇺🇿', label: 'Oʻzbekcha', locale: 'uz-UZ' },
    { code: 'mn', flag: '🇲🇳', label: 'Монгол', locale: 'mn-MN' },
    { code: 'sq', flag: '🇦🇱', label: 'Shqip', locale: 'sq-AL' },
    { code: 'mk', flag: '🇲🇰', label: 'Македонски', locale: 'mk-MK' },
    { code: 'sr', flag: '🇷🇸', label: 'Српски', locale: 'sr-RS' },
    { code: 'is', flag: '🇮🇸', label: 'Íslenska', locale: 'is-IS' },
    { code: 'ga', flag: '🇮🇪', label: 'Gaeilge', locale: 'ga-IE' },
    { code: 'cy', flag: '🇬🇧', label: 'Cymraeg', locale: 'cy-GB' },
    { code: 'eu', flag: '🇪🇸', label: 'Euskara', locale: 'eu-ES' },
    { code: 'gl', flag: '🇪🇸', label: 'Galego', locale: 'gl-ES' },
    { code: 'ca', flag: '🇪🇸', label: 'Català', locale: 'ca-ES' },
    { code: 'af', flag: '🇿🇦', label: 'Afrikaans', locale: 'af-ZA' },
    { code: 'zu', flag: '🇿🇦', label: 'isiZulu', locale: 'zu-ZA' },
    { code: 'xh', flag: '🇿🇦', label: 'isiXhosa', locale: 'xh-ZA' },
    { code: 'am', flag: '🇪🇹', label: 'አማርኛ', locale: 'am-ET' }
];
